### ISSUE TITLE
是否已经失效

### ISSUE THREAD

**Issue by sudoyang** [gyjyywc/hide-hot-content#1]
安装后无效

**Comment by yywc** [comment]
没有呀，我刚试了下还可以。是 Chrome 下使用情景吗？

**Comment by yywc** [comment]
@sudoyang 没有呀，我刚试了下还可以。是 Chrome 下使用情景吗？

**Comment by sudoyang** [comment]
火狐下面无效 chrome刚刚试了 没问题

**Comment by sudoyang** [comment]
Tampermonkey + firefox没问题 violentmonkey在firefox就不行

**Comment by yywc** [comment]
@sudoyang 噢，我刚才试了下也是可以的。60.0.1 (64 位) firefox，violentmonkey 的话没有使用过就不清楚了。
